version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: mops-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  minio:
    image: minio/minio:latest
    container_name: mops-minio
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

  minio-init:
    image: minio/mc:latest
    container_name: mops-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/datalake || true;
      /usr/bin/mc mb myminio/datalake-vl || true;
      /usr/bin/mc mb myminio/models || true;
      exit 0;
      "

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: mops-api
    ports:
      - "8001:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATA_LAKE_PATH=/app/data/lake
      - MODELS_OUTPUT_PATH=/app/data/models
      - MINIO_ENDPOINT=minio:9000             # interno Docker
      # ⚠️ PRODUCCIÓN: reemplaza con la IP pública del Server B para que el Edge descargue los LoRAs
      - MINIO_EXTERNAL_ENDPOINT=${MINIO_EXTERNAL_ENDPOINT:-38.128.233.165:9002}
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - API_KEY=${MOTHERSHIP_API_KEY:-default-mothership-secret-key}
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - hf_cache:/app/data/huggingface_cache
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: mops-gpu-worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATA_LAKE_PATH=/app/data/lake
      - MODELS_OUTPUT_PATH=/app/data/models
      - MINIO_ENDPOINT=minio:9000
      - MINIO_EXTERNAL_ENDPOINT=${MINIO_EXTERNAL_ENDPOINT:-38.128.233.165:9002}
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - API_KEY=${MOTHERSHIP_API_KEY:-default-mothership-secret-key}
      # Necesario para Unsloth/Transformers para que no descarguen al contenedor temporal
      - HF_HOME=/app/data/huggingface_cache
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - hf_cache:/app/data/huggingface_cache
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  redis_data:
  minio_data:
  hf_cache:
